apiVersion: v1
kind: Service
metadata:
  name: api-riesgo-proveedores
  labels:
    app: api-riesgo-proveedores
spec:
  type: ClusterIP
  selector:
    app: api-riesgo-proveedores
  ports:
    - name: http
      port: 9541
      targetPort: 9541
